<a href="https://colab.research.google.com/github/MUDULURUGAYATHRIVARMA/DDL-and-DML-commands-for-pride/blob/main/MovieRecommendationSystem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as ny
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
moviesdata=pd.read_csv('/content/movies.csv')

In [6]:
moviesdata.head()

index     budget  ...                                               crew           director
0      0  237000000  ...  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1      1  300000000  ...  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2      2  245000000  ...  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3      3  250000000  ...  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4      4  260000000  ...  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton

[5 rows x 24 columns]

In [7]:
moviesdata.shape

(4803, 24)

In [8]:
selected_features=['genres','keywords','tagline','cast','director','overview']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director', 'overview']


In [10]:
#fillna() method will replaces null values with specified valus
for feature in selected_features:
  moviesdata[feature]=moviesdata[feature].fillna('')

In [11]:
combine_selected_features=moviesdata['genres']+' '+moviesdata['keywords']+' '+moviesdata['tagline']+' '+moviesdata['cast']+' '+moviesdata['director']+' '+moviesdata['overview']

In [14]:
print(combine_selected_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [16]:
#converting the text to feature vector (numeric values) beacause with help of numeric values we can easily find the cosine similarity
vectorizer=TfidfVectorizer()

In [17]:
feature_vector = vectorizer.fit_transform(combine_selected_features)
print(feature_vector)

  (0, 561)	0.05971816344971169
  (0, 703)	0.06846420517510078
  (0, 9754)	0.08513696797398294
  (0, 23977)	0.07941905576010944
  (0, 10023)	0.07960231361105431
  (0, 6601)	0.1498786462809525
  (0, 5279)	0.1549075340655008
  (0, 10796)	0.11095111375730655
  (0, 25413)	0.24369151759694266
  (0, 29469)	0.08637114089261566
  (0, 5592)	0.17322386697661618
  (0, 25232)	0.1336739112380023
  (0, 9065)	0.14505772980982928
  (0, 27118)	0.08328687324810813
  (0, 30121)	0.07272849549697494
  (0, 19410)	0.0318696249813729
  (0, 20039)	0.37747447361884223
  (0, 23619)	0.11047375838269538
  (0, 30145)	0.18243919685121024
  (0, 30543)	0.15064979633862852
  (0, 23578)	0.16802034155542864
  (0, 24802)	0.158925784923944
  (0, 29614)	0.15064979633862852
  (0, 25868)	0.11590870590502833
  (0, 15569)	0.171366691592621
  :	:
  (4802, 9588)	0.10415492266309316
  (4802, 21386)	0.08975511036766048
  (4802, 9166)	0.07829183421073847
  (4802, 24102)	0.08207980733784753
  (4802, 6136)	0.10774075928383217
  (4802, 

In [19]:
#to find similarity between user input and dataset we use cosine similarity
similarity=cosine_similarity(feature_vector)
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [20]:
print(similarity.shape)

(4803, 4803)


In [21]:
#now getting input from user
moviename=input("Enter your any movie name:")

Enter your any movie name:spider man


In [22]:
#now taking only list of all movie names to compare with user input
list_movies=moviesdata['title'].tolist()
print(list_movies)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [23]:
# now we are going to find similar or closer to movie tilte with user input
finding_close_movie=difflib.get_close_matches(moviename,list_movies)
print(finding_close_movie)

['Spider-Man', 'Inside Man', 'Superman']


In [24]:
close_match=finding_close_movie[0]
print(close_match)

Spider-Man


In [26]:
#finding index of movie by using title of movie
index_of_movie=moviesdata[moviesdata.title==close_match]['index'].values[0]
print(index_of_movie)

159


In [27]:
# find similar movies based on index values
similarity_score=list(enumerate(similarity[index_of_movie]))
print(similarity_score)


[(0, 0.033410132701211376), (1, 0.02155288412907901), (2, 0.01573476797029399), (3, 0.03017223147128505), (4, 0.04630937312487815), (5, 0.3316548194452161), (6, 0.015459007138838623), (7, 0.007868761016055402), (8, 0.01893721459068837), (9, 0.020693400149093003), (10, 0.03372456679496629), (11, 0.018001434467822063), (12, 0.019103790953882805), (13, 0.017652468318506503), (14, 0.03168424748735248), (15, 0.03175463450220474), (16, 0.005981697525448927), (17, 0.013452552827417627), (18, 0.009450281126779201), (19, 0.025908429524434447), (20, 0.11989084689930171), (21, 0.004780815773898551), (22, 0.015735937413798883), (23, 0.023510086722979457), (24, 0.01955219115285731), (25, 0.006596464162915545), (26, 0.009708115873933339), (27, 0.02123657029398566), (28, 0.013259919419896777), (29, 0.02541076520075808), (30, 0.26424462628281137), (31, 0.024162568246942736), (32, 0.021104153544064266), (33, 0.006402192684496155), (34, 0.011255349324438084), (35, 0.02639757047576602), (36, 0.0076687346

In [29]:
len(similarity_score)

4803

In [35]:
#sorting the movies acording to their similarities
sorting_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorting_movies)

[(159, 1.0000000000000004), (5, 0.3316548194452161), (30, 0.26424462628281137), (1534, 0.2070474411782685), (38, 0.12722073360097494), (431, 0.12267515598449447), (20, 0.11989084689930171), (37, 0.10323191934002364), (1796, 0.09576332899359533), (1523, 0.09419279504731681), (767, 0.09408033158665655), (3265, 0.09391911363717476), (2375, 0.09117776397811046), (1119, 0.0888786055504274), (2361, 0.08880201419832945), (2163, 0.08760973351617557), (953, 0.08744494623831751), (1559, 0.08631726463196232), (259, 0.08622194909791323), (382, 0.08426705068249934), (2183, 0.08201194357117281), (3044, 0.08188413849254814), (3949, 0.07904289740127948), (677, 0.07623670012212817), (1793, 0.07617688549159317), (3479, 0.07582738747412511), (3124, 0.074649238760739), (328, 0.0724068718815645), (1427, 0.07203986333226402), (2740, 0.07189406252950187), (2218, 0.07024502505211684), (2157, 0.06985062335788439), (3155, 0.06949939717179829), (3383, 0.06816089909449102), (1193, 0.06723594545043532), (1699, 0.0

In [46]:
# now we are printing all similar movies using  their index
print("These are few relevent movie_titles according to your search:\n")
i=1
for movie in sorting_movies:
  index = movie[0]
  total_movies=moviesdata[moviesdata.index==index]['title'].values[0]
  if(i<=30):
    print(i,'.',total_movies)
    i+=1




These are few relevent movie_titles according to your search:

1 . The Avengers
2 . Avengers: Age of Ultron
3 . Captain America: The Winter Soldier
4 . Iron Man 2
5 . Captain America: Civil War
6 . X-Men
7 . The Incredible Hulk
8 . Thor: The Dark World
9 . X-Men: Apocalypse
10 . Captain America: The First Avenger
11 . X-Men: Days of Future Past
12 . Ant-Man
13 . Iron Man 3
14 . X-Men: The Last Stand
15 . Iron Man
16 . X-Men: First Class
17 . Thor
18 . X2
19 . Man of Steel
20 . The Amazing Spider-Man 2
21 . Kick-Ass
22 . Superman II
23 . Serenity
24 . Guardians of the Galaxy
25 . The Shadow
26 . Fantastic 4: Rise of the Silver Surfer
27 . Deadpool
28 . The Losers
29 . The Spirit
30 . The Horse Whisperer


Movie Recommendation System


In [47]:
moviename=input("Enter your any movie name:")

list_movies=moviesdata['title'].tolist()

finding_close_movie=difflib.get_close_matches(moviename,list_movies)

close_match=finding_close_movie[0]

index_of_movie=moviesdata[moviesdata.title==close_match]['index'].values[0]

similarity_score=list(enumerate(similarity[index_of_movie]))

sorting_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)

print("\nThese are few relevent movie_titles according to your search:\n")
i=1
for movie in sorting_movies:
  index = movie[0]
  total_movies=moviesdata[moviesdata.index==index]['title'].values[0]
  if(i<=30):
    print(i,'.',total_movies)
    i+=1



Enter your any movie name:happy

These are few relevent movie_titles according to your search:

1 . Chappie
2 . Bicentennial Man
3 . The Elephant Man
4 . Robot & Frank
5 . Automata
6 . Ex Machina
7 . A.I. Artificial Intelligence
8 . Real Steel
9 . Terminator 3: Rise of the Machines
10 . Terminator Genisys
11 . RoboCop
12 . My Name Is Khan
13 . Elysium
14 . WALL·E
15 . Astro Boy
16 . Robots
17 . Bill & Ted's Bogus Journey
18 . Crank
19 . 1982
20 . I, Robot
21 . Ninja Assassin
22 . Man of Steel
23 . Transformers: Age of Extinction
24 . A Thousand Words
25 . The Dead Zone
26 . Sky Captain and the World of Tomorrow
27 . What Dreams May Come
28 . Repo Men
29 . The Black Hole
30 . Ender's Game
